# define datastores for data loading
datastores:
  - jdbc: jdbc:mysql://localhost/d012dad2
    user: root
    pwd: 
    table: accesslog
    columns: 
        - name : path
          type : java.lang.String
        - name : hostname
          type : java.lang.String          
        - name : title
          type : java.lang.String
        - name : url
          type : java.lang.String
        - name : timer
          type : java.lang.Integer
        - name : timestamp
          type : java.lang.Long
    